server:
  port: 7999
spring:
  application:
    name: zkm-resource
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates
  datasource:
    username: root
    password: 1235789k
    url: jdbc:mysql://localhost:3306/zkm
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    password: 123456
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        min-idle: 0
        max-idle: 8
    timeout: 1000
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.zkm.model
zkm:
  jwt:
    header: Authorization
    expire: 604800 # 7天，s为单位
    secret: abcdefghabcdefghabcdefghabcdefgh

OPENVIDU_URL: http://localhost:4443/
OPENVIDU_SECRET: MY_SECRET


